/* eslint-disable */
const fs = require('fs');
const path = require('path');

const apiUrl = process.env.API_URL || 'http://localhost:3000/api';
const socketUrl = process.env.SOCKET_URL || '';
const supabaseUrl =
  process.env.SUPABASE_URL ||
  'https://hyijalbbdxovyblyscxm.supabase.co';
const supabaseAnonKey =
  process.env.SUPABASE_ANON_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5aWphbGJiZHhvdnlibHlzY3htIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxMTg1NTYsImV4cCI6MjA4NTY5NDU1Nn0.-0Y0MXUIWa3Y4Y9pNWf0tV_CYBA4N8kuyIXzjy6QBfU';
const datadogRumAppId = process.env.DD_RUM_APP_ID || '';
const datadogRumClientToken = process.env.DD_RUM_CLIENT_TOKEN || '';
const datadogSite = process.env.DD_SITE || 'ap2.datadoghq.com';

const contents = `// AUTO-GENERATED by scripts/generate-env.js — do not edit by hand.
// Values are sourced from env vars at build time.
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
  socketUrl: '${socketUrl}',
  supabaseUrl: '${supabaseUrl}',
  supabaseAnonKey: '${supabaseAnonKey}',
  datadogRumAppId: '${datadogRumAppId}',
  datadogRumClientToken: '${datadogRumClientToken}',
  datadogSite: '${datadogSite}',
};
`;

const target = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
fs.writeFileSync(target, contents, 'utf8');
console.log(`[generate-env] wrote ${target} (apiUrl=${apiUrl})`);
