-- Spring Boot manages its own UUIDs — public.users must NOT be a FK slave to auth.users.
-- Migration 010 tried `DROP CONSTRAINT IF EXISTS users_id_fkey`, but Supabase may have
-- generated a different constraint name. This migration finds and drops the FK regardless.
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT tc.constraint_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.referential_constraints rc
            ON tc.constraint_name = rc.constraint_name
        JOIN information_schema.constraint_column_usage ccu
            ON rc.unique_constraint_name = ccu.constraint_name
        WHERE tc.table_schema = 'public'
          AND tc.table_name   = 'users'
          AND tc.constraint_type = 'FOREIGN KEY'
          AND ccu.table_schema   = 'auth'
          AND ccu.table_name     = 'users'
    LOOP
        EXECUTE format('ALTER TABLE public.users DROP CONSTRAINT %I', r.constraint_name);
        RAISE NOTICE 'Dropped FK constraint: %', r.constraint_name;
    END LOOP;
END $$;

-- Belt-and-suspenders: also try the expected name in case the DO block misses edge cases.
ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_id_fkey;

-- Set Spring Boot-compatible BCrypt password hash for the main admin account.
-- Hash is bcrypt(cost=10) of the real password — generated by the backend bcrypt library.
UPDATE public.users
SET password_hash = '$2b$10$VFS9b93zWH.MTirDtigU1OVF8f/nL0A9.apFXXBVlkzwkLEYinnmm'
WHERE email = 'dinhdaivu1109@gmail.com'
  AND (password_hash IS NULL OR password_hash = '');
